name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0
         
      - name: Gradle caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')}}
          restore-keys: |
            ${{runner.os}}-gradle-

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #- name: Create LOCAL_PROPERTIES
      #  run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: JUSICOOL Android CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ JusiCool-Android-CI 성공! ✅
          webhook: ${{ secrets.JUSICOOL_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.SUCCESS_IMAGE }}
          description: 각하..성공했긔..
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: JusiCool CI 봇

      - name: JUSICOOL Android CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ JusiCool-Android-CI 실패! ❗️
          webhook: ${{ secrets.JUSICOOL_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.FAILED_IMAGE }}
          description: 실패해버렸긔..
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: JusiCool CI 봇
