name: Zimperium zScan

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  zscan:
    name: zScan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-levels: 30
          build-tools: 30.0.3

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > $GITHUB_WORKSPACE/local.properties
        
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Execute gradle build
        run: ./gradlew build

      - name: Run Zimperium zScan
        uses: zimperium/zscanmarketplace@v1
        timeout-minutes: 60
        with:
          client_env: mapsfreemium
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.ZSCAN_CLIENT_SECRET }}
          app_file: ./InsecureBankv2.apk

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: Zimperium.sarif
